### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [TeamKizinLakay/KizinLakay#1]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough), so this week (Sprint 1 review) your team should complete the first 50% of the core app functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for internal demo day.

As far as the process goes, try to break down each of your stories/app features into smaller tasks (create issues) and assign it to your team members so that each team member has a clear idea on what they have to work on.

Excited to see what your group comes up with!

N.B.- Please give a name to your group.

**Comment by codepathreview** [comment]
:+1: Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:

It is important create tasks for each of your stories/features and have them assigned to team members in the form of issues. Please take care of this before you work on sprint 2

Consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.

Good job by everyone to contribute to the project.

Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you group all detailed issues into milestones representing sprints so that its easier for you to track progress of the project.

Consider creating tasks to complete the creation of your database schema and its respective models. 

Depending on the strategy your group has come up with, consider creating regular pushes/pull-requests to sync up your code to avoid having multiple errors at the end.

Consider creating group milestones/pull requests to better track your progress and review each others code.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.

 
/cc @codepathreview

**Comment by tayousyl** [comment]
Received...
